# Generated by Django 3.1.3 on 2021-06-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Agent2',
        ),
        migrations.DeleteModel(
            name='BrainPost',
        ),
        migrations.DeleteModel(
            name='BrainTag',
        ),
        migrations.DeleteModel(
            name='BrainUser',
        ),
        migrations.DeleteModel(
            name='NaverComment',
        ),
        migrations.DeleteModel(
            name='NaverPost',
        ),
        migrations.DeleteModel(
            name='NaverTag',
        ),
    ]
