# Generated by Django 3.1.3 on 2021-06-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_agent_agent2_blogcomment_blogpost_brainpost_braintag_brainuser_navercomment_naverpost_navertag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naverpost',
            name='naver_postcol',
        ),
    ]
