# Generated by Django 3.1.3 on 2021-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_remove_naverpost_naver_postcol'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(blank=True, max_length=45, null=True)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('like_count', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'insta_post',
            },
        ),
        migrations.CreateModel(
            name='InstaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=45, null=True)),
                ('tag', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'insta_tag',
            },
        ),
        migrations.AlterModelOptions(
            name='navercomment',
            options={},
        ),
    ]
