# Generated by Django 3.1.3 on 2021-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20210604_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Agent2',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='BrainPost',
        ),
        migrations.DeleteModel(
            name='BrainTag',
        ),
        migrations.DeleteModel(
            name='BrainUser',
        ),
        migrations.DeleteModel(
            name='NaverTag',
        ),
        migrations.AlterModelOptions(
            name='navercomment',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='instapost',
            name='like_count',
            field=models.IntegerField(),
        ),
    ]
