# Generated by Django 3.1.3 on 2021-06-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20210604_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instatag',
            old_name='post_id',
            new_name='short_code',
        ),
    ]
