# Generated by Django 3.1.3 on 2021-06-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20210604_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInstagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('author', models.CharField(blank=True, max_length=45, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'post_instagram',
            },
        ),
        migrations.CreateModel(
            name='PostInstagramTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=45, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'post_instagram_tag',
            },
        ),
        migrations.CreateModel(
            name='PostNaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('bc_id', models.CharField(blank=True, max_length=45, null=True)),
                ('author', models.CharField(blank=True, max_length=45, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'post_naver',
            },
        ),
        migrations.CreateModel(
            name='PostNaverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'post_naver_image',
            },
        ),
        migrations.CreateModel(
            name='PostNaverTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=45, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'post_naver_tag',
            },
        ),
        migrations.AddField(
            model_name='instatag',
            name='count',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
