# Generated by Django 3.1.3 on 2021-06-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20210621_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postinstagram',
            options={'verbose_name': '인스타그램 포스트', 'verbose_name_plural': '인스타그램 포스트'},
        ),
        migrations.AlterModelOptions(
            name='postinstagramtag',
            options={'verbose_name': '인스타그램 포스트 태그', 'verbose_name_plural': '인스타그램 포스트 태그'},
        ),
        migrations.AlterModelOptions(
            name='postnaver',
            options={'verbose_name': '네이버 포스트', 'verbose_name_plural': '네이버 포스트'},
        ),
        migrations.AlterModelOptions(
            name='postnaverimage',
            options={'verbose_name': '네이버 포스트 이미지', 'verbose_name_plural': '네이버 포스트 이미지'},
        ),
        migrations.AlterModelOptions(
            name='postnavertag',
            options={'verbose_name': '네이버 포스트 태그', 'verbose_name_plural': '네이버 포스트 태그'},
        ),
    ]
