# Generated by Django 3.1.3 on 2021-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_auto_20210621_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinstagram',
            name='is_bad_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postinstagram',
            name='is_good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postnaver',
            name='is_bad_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postnaver',
            name='is_good_count',
            field=models.IntegerField(default=0),
        ),
    ]
