# Generated by Django 3.1.3 on 2021-07-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_auto_20210622_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=45, unique=True, verbose_name='포스트아이디')),
                ('domain', models.CharField(blank=True, max_length=45, null=True, verbose_name='도메인')),
                ('bc_id', models.CharField(blank=True, max_length=45, null=True, verbose_name='블로그/카페아이디')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='작성자')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='작성일')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='본문주소')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='숨김여부')),
            ],
        ),
        migrations.CreateModel(
            name='HashPostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.hashpost')),
            ],
        ),
        migrations.CreateModel(
            name='HashPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.hashpost')),
            ],
        ),
    ]
