# Generated by Django 3.1.3 on 2021-07-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_hashpost_hashpostimage_hashposttag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashpost',
            options={'verbose_name': '포스트', 'verbose_name_plural': '포스트'},
        ),
        migrations.AlterModelOptions(
            name='hashpostimage',
            options={'verbose_name': '이미지', 'verbose_name_plural': '이미지'},
        ),
        migrations.AlterModelOptions(
            name='hashposttag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterModelTable(
            name='hashpost',
            table='hash_post',
        ),
        migrations.AlterModelTable(
            name='hashpostimage',
            table='hash_post_image',
        ),
        migrations.AlterModelTable(
            name='hashposttag',
            table='hash_post_tag',
        ),
    ]
