# Generated by Django 3.1.3 on 2021-07-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0012_auto_20210706_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashpostimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='hashposttag',
            name='post',
        ),
        migrations.DeleteModel(
            name='HashPost',
        ),
        migrations.DeleteModel(
            name='HashPostImage',
        ),
        migrations.DeleteModel(
            name='HashPostTag',
        ),
    ]
