# Generated by Django 3.1.3 on 2021-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0014_hashpost_hashpostimage_hashposttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashpostimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='hashposttag',
            name='post',
        ),
        migrations.AddField(
            model_name='hashpostimage',
            name='post_id',
            field=models.CharField(default='default', max_length=45, verbose_name='포스트아이디'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashposttag',
            name='post_id',
            field=models.CharField(default='default', max_length=45, verbose_name='포스트아이디'),
            preserve_default=False,
        ),
    ]
