# Generated by Django 3.1.3 on 2021-01-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team_id',
            new_name='team',
        ),
    ]
