# Generated by Django 3.1.3 on 2021-01-13 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_auto_20210113_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type_data', models.CharField(choices=[('0', 'Positive'), ('1', 'Negative'), ('2', 'Binary')], default='0', max_length=1, verbose_name='Type')),
                ('obtained', models.FloatField(default=0)),
                ('expected', models.FloatField()),
                ('percentage', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='publication date')),
            ],
        ),
        migrations.CreateModel(
            name='OkrProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField()),
                ('memo', models.CharField(max_length=500)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrprogress', to='okr.keyresult')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rate', models.FloatField()),
                ('data_type', models.CharField(choices=[('int', '정수'), ('float', '실수'), ('percent', '백분율')], max_length=15)),
                ('type', models.CharField(choices=[('0', 'Challenge'), ('1', 'Necessary'), ('2', 'Personal')], default='1', max_length=1, verbose_name='Type')),
                ('created_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_leader', to='okr.user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_team', to='okr.team')),
            ],
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyresult', to='okr.objective'),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_user', to='okr.user'),
        ),
    ]
