# Generated by Django 3.1.3 on 2021-01-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0003_auto_20210113_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyresult',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='okrprogress',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
