# Generated by Django 3.1.3 on 2021-01-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0004_auto_20210113_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
