# Generated by Django 3.1.3 on 2021-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0005_auto_20210113_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='okrprogress',
            old_name='create_at',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
