# Generated by Django 3.1.3 on 2021-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201230_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_post',
            field=models.BooleanField(default=True),
        ),
    ]
