# Generated by Django 3.1.3 on 2021-04-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_approved_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
